<?php

declare(strict_types=1);

namespace ProLab\Database;

use PDO;

/**
 * Migração idempotente do schema — corre a cada arranque (CREATE TABLE IF NOT EXISTS).
 * Mantém os três dialetos num único lugar.
 */
final class Schema
{
    public static function migrate(PDO $pdo, string $driver): void
    {
        foreach (self::statements($driver) as $sql) {
            $pdo->exec($sql);
        }
    }

    /** @return string[] */
    private static function statements(string $driver): array
    {
        return match ($driver) {
            'pgsql' => [
                'CREATE TABLE IF NOT EXISTS users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    email VARCHAR(190) NOT NULL UNIQUE,
                    password_hash VARCHAR(255) NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
                )',
                'CREATE TABLE IF NOT EXISTS profiles (
                    user_id BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
                    age INT,
                    weight_kg NUMERIC(5,2),
                    height_m NUMERIC(4,2),
                    objective VARCHAR(20),
                    level VARCHAR(20) NOT NULL DEFAULT \'iniciante\',
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
                )',
                'CREATE TABLE IF NOT EXISTS measurements (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                    weight_kg NUMERIC(5,2),
                    height_m NUMERIC(4,2),
                    bmi NUMERIC(5,2),
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
                )',
                'CREATE INDEX IF NOT EXISTS idx_measurements_user
                    ON measurements (user_id, created_at)',
                'CREATE TABLE IF NOT EXISTS checklists (
                    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                    week_key VARCHAR(10) NOT NULL,
                    items TEXT NOT NULL,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    PRIMARY KEY (user_id, week_key)
                )',
            ],

            'mysql' => [
                'CREATE TABLE IF NOT EXISTS users (
                    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                    name VARCHAR(100) NOT NULL,
                    email VARCHAR(190) NOT NULL,
                    password_hash VARCHAR(255) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (id),
                    UNIQUE KEY uq_users_email (email)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
                'CREATE TABLE IF NOT EXISTS profiles (
                    user_id INT UNSIGNED NOT NULL,
                    age INT NULL,
                    weight_kg DECIMAL(5,2) NULL,
                    height_m DECIMAL(4,2) NULL,
                    objective VARCHAR(20) NULL,
                    level VARCHAR(20) NOT NULL DEFAULT \'iniciante\',
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                        ON UPDATE CURRENT_TIMESTAMP,
                    PRIMARY KEY (user_id),
                    CONSTRAINT fk_profiles_user FOREIGN KEY (user_id)
                        REFERENCES users (id) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
                'CREATE TABLE IF NOT EXISTS measurements (
                    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
                    user_id INT UNSIGNED NOT NULL,
                    weight_kg DECIMAL(5,2) NULL,
                    height_m DECIMAL(4,2) NULL,
                    bmi DECIMAL(5,2) NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (id),
                    KEY idx_measurements_user (user_id, created_at),
                    CONSTRAINT fk_measurements_user FOREIGN KEY (user_id)
                        REFERENCES users (id) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
                'CREATE TABLE IF NOT EXISTS checklists (
                    user_id INT UNSIGNED NOT NULL,
                    week_key VARCHAR(10) NOT NULL,
                    items TEXT NOT NULL,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                        ON UPDATE CURRENT_TIMESTAMP,
                    PRIMARY KEY (user_id, week_key),
                    CONSTRAINT fk_checklists_user FOREIGN KEY (user_id)
                        REFERENCES users (id) ON DELETE CASCADE
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci',
            ],

            default => [
                'CREATE TABLE IF NOT EXISTS users (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    name TEXT NOT NULL,
                    email TEXT NOT NULL UNIQUE,
                    password_hash TEXT NOT NULL,
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )',
                'CREATE TABLE IF NOT EXISTS profiles (
                    user_id INTEGER PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
                    age INTEGER,
                    weight_kg REAL,
                    height_m REAL,
                    objective TEXT,
                    level TEXT NOT NULL DEFAULT \'iniciante\',
                    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )',
                'CREATE TABLE IF NOT EXISTS measurements (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                    weight_kg REAL,
                    height_m REAL,
                    bmi REAL,
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )',
                'CREATE INDEX IF NOT EXISTS idx_measurements_user
                    ON measurements (user_id, created_at)',
                'CREATE TABLE IF NOT EXISTS checklists (
                    user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                    week_key TEXT NOT NULL,
                    items TEXT NOT NULL,
                    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (user_id, week_key)
                )',
            ],
        };
    }
}
